pages:
  image: node:lts

  before_script:
    - npm ci

  script:
    - npm run build

  artifacts:
    paths:
      - public

  only:
    - main

check_lockfile:
  image: node:lts
  stage: test
  script:
    - npm ci
    - npm install --package-lock-only
    - |
      if ! git diff --quiet package-lock.json; then
        echo "package-lock.json is out of date. Run 'npm install' and commit the changes."
        exit 1
      fi
  only:
    - main
